"""Markdown and JSON report generators.

Renders NarrativeReport into output formats:
- Markdown: human-readable with headers, citations, and origin labels
- JSON: structured for API responses and frontend rendering
- Future: PDF export via markdown → PDF pipeline
"""

from __future__ import annotations

import json
from datetime import datetime
from typing import Any

from narrative.engine import NarrativeReport, NarrativeSection


def to_markdown(report: NarrativeReport) -> str:
    """Render a NarrativeReport as markdown."""
    lines = [
        f"# Pharmacogenomic Analysis Report",
        f"",
        f"> **Audience:** {report.audience.value.title()} | "
        f"**Generated:** {report.generated_at.strftime('%Y-%m-%d %H:%M UTC')} | "
        f"**Correlation:** {report.correlation_id}",
        "",
        "> ⚠️ Research only — not for clinical decision-making.",
        "",
    ]

    for section in report.sections:
        # Origin label
        origin_badge = "🔬 ESTABLISHED" if section.origin == "deterministic" else "📝 NARRATIVE"
        conf_str = f" | Confidence: {section.confidence:.2f}" if section.confidence < 1.0 else ""

        lines.append(f"## {section.title}")
        lines.append(f"*[{origin_badge}{conf_str}]*")
        lines.append("")
        lines.append(section.content)

        # Citations
        if section.citations:
            cites = [c for c in section.citations if c]
            if cites:
                lines.append("")
                lines.append(f"*Sources: {', '.join(cites)}*")

        # Uncertainty
        if section.uncertainty_note:
            lines.append("")
            lines.append(f"⚠️ **Note:** {section.uncertainty_note}")

        lines.append("")

    lines.extend([
        "---",
        "*Generated by Anukriti Swarm. Every claim is evidence-backed and traceable.*",
    ])

    return "\n".join(lines)


def to_json(report: NarrativeReport) -> str:
    """Render a NarrativeReport as structured JSON."""
    data = {
        "report_type": "pharmacogenomic_analysis",
        "audience": report.audience.value,
        "correlation_id": report.correlation_id,
        "generated_at": report.generated_at.isoformat(),
        "sections": [
            {
                "title": s.title,
                "content": s.content,
                "origin": s.origin,
                "citations": [c for c in s.citations if c],
                "confidence": s.confidence,
                "uncertainty_note": s.uncertainty_note,
            }
            for s in report.sections
        ],
        "metadata": {
            "total_sections": len(report.sections),
            "deterministic_sections": sum(1 for s in report.sections if s.origin == "deterministic"),
            "narrative_sections": sum(1 for s in report.sections if s.origin == "narrative"),
            "all_citations": sorted(set(c for s in report.sections for c in s.citations if c)),
        },
    }
    return json.dumps(data, indent=2, default=str)
